# Generated by Django 6.0.3 on 2026-05-21 08:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="amount",
        ),
        migrations.AddField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
