# Generated by Django 6.0.3 on 2026-05-21 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("UserApp", "0002_order_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="amount",
            new_name="real_amount",
        ),
    ]
