# Generated by Django 6.0.3 on 2026-05-15 06:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserApp", "0005_rename_schedule_service_booking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="user",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="Phone",
        ),
        migrations.RemoveField(
            model_name="service_booking",
            name="category",
        ),
        migrations.AddField(
            model_name="message",
            name="name",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="service_booking",
            name="Delivery_mode",
            field=models.CharField(
                choices=[("Normal", "Normal"), ("Express", "Express")],
                default="Normal",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="service_booking",
            name="order_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="service_booking",
            name="size",
            field=models.CharField(
                choices=[("small", "Small"), ("large", "Large"), ("others", "Others")],
                default="small",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="service_booking",
            name="time",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="service_booking",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "stripe_payment_intent",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
