# Generated by Django 6.0.3 on 2026-05-18 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_remove_message_user_remove_profile_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_booking',
            name='Delivery_mode',
        ),
        migrations.RemoveField(
            model_name='service_booking',
            name='service',
        ),
        migrations.RemoveField(
            model_name='service_booking',
            name='size',
        ),
    ]
