# Generated by Django 6.0.3 on 2026-05-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserApp", "0007_remove_service_booking_delivery_mode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service_booking",
            name="phone",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="service_booking",
            name="street_address",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="service_booking",
            name="time",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="service_booking",
            name="zipcode",
            field=models.CharField(max_length=20),
        ),
    ]
