# Generated by Django 6.0.3 on 2026-05-19 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserApp", "0008_alter_service_booking_phone_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="order",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
        migrations.RemoveField(
            model_name="order",
            name="stripe_payment_intent",
        ),
        migrations.AddField(
            model_name="order",
            name="Bag_type",
            field=models.CharField(
                choices=[("small", "Small Bag"), ("large", "Large Bag")],
                default="small",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="Delivery_Type",
            field=models.CharField(
                choices=[
                    ("normal", "Normal Delivery"),
                    ("express", "Express Delivery"),
                ],
                default="small",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
